const VARIABLES_LIST = [
  'NEXT_PUBLIC_REGION',
  'NEXT_PUBLIC_CLIENT_ID',
  'NEXT_PUBLIC_AG_GRID_KEY',
  'NEXT_PUBLIC_USERPOOL_ID',
  'NEXT_PUBLIC_REDIRECT_URL',
  'NEXT_PUBLIC_INFRA_EDGE_URL',
  'NEXT_PUBLIC_COGNITO_DOMAIN',
  'NEXT_PUBLIC_MAIN_BUCKET_URL',
  'NEXT_PUBLIC_INFRA_BACKEND_URL',
  'LT_USERNAME',
  'LT_ACCESS_KEY',
];

export { VARIABLES_LIST };
